### ISSUE TITLE
support for create new branch

### ISSUE THREAD

**Issue by tp99** [lvrfrc87/git-acp-ansible#2]
Thank you for writing this module. I’m trying to use this to automatically update some config files but running into couple of issues. I’m hoping you have already solved it and just haven’t documented it.
 
First, how do you create a new branch when using this module? I would like to create a new branch, edit some files and push it back. It seems like I have to use shell module to create a branch now. Is there anyway to do it with a module?

Second, when mode=ssh, why do you require url to start with git@... ? Mine is failing with that format since I use ssh://git@... in .git/commit config file. I commented out that requirement in git_acp.py and it works fine.

**Comment by tp99** [comment]
Thank you for your reply, I'm using bitbucket but I believe all git repos support this format.

See this: https://confluence.atlassian.com/bitbucket/change-the-remote-url-to-your-repository-794212774.html

Also, please consider adding create branch option so it can be handled by one module.

**Comment by lvrfrc87** [comment]
Looking at your link, git repo in bit bucket accept either `ssh://git@` as well as `git@` so the module is compatible if used the appropriated URL. Regarding your feature request, I do not see create a new branch as part of `add/commit/push` so I would not integrate rather then create a separate module for that. If can be useful, I checkout a new branch in this way.

```
        - name: GIT | find branch.
          shell: "git branch --list {{ branch }}"
          register: result
          tags: git

        - name: GIT | checkout branch if required.
          shell: "git checkout -b {{ branch }}"
          when: branch not in result.stdout
          tags: git
```

**Comment by lvrfrc87** [comment]
I have updated a fix for `ssh//git@`. Please install `1.0.5` and let me know

`pip3 install git-acp-ansible==1.0.5`

**Comment by tp99** [comment]
Thanks @lvrfrc87 There is a logic error in that if not statement. I've fixed it locally. If you give me push access (collaborator) I would like to push the fix to your repo.

https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

**Comment by lvrfrc87** [comment]
@tp99 you have to fork the repo, push the update and then submit a PR

https://help.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by lvrfrc87** [comment]
@tp99 Version 1.0.6 released. Can you please install and give a try?

**Comment by tp99** [comment]
@lvrfrc87 I tried to install with following command but it says "No matching distribution found"

`pip3 install git-acp-ansible==1.0.6`

**Comment by lvrfrc87** [comment]
Try again. Sometimes I see pip fail when you install a new package for the first time. Is ok for me.

```
olivierif:git-acp-ansible federicoolivieri$ pip3 install git-acp-ansible==1.0.6
Collecting git-acp-ansible==1.0.6
  Downloading https://files.pythonhosted.org/packages/46/68/17285293a252931eaa5b6177dc93ab6087b2244a41f0f61ca388aa5ac3fe/git_acp_ansible-1.0.6-py3-none-any.whl
Requirement already satisfied: ansible in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from git-acp-ansible==1.0.6) (2.9.7)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ansible->git-acp-ansible==1.0.6) (2.11.2)
Requirement already satisfied: cryptography in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ansible->git-acp-ansible==1.0.6) (2.9.2)
Requirement already satisfied: PyYAML in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ansible->git-acp-ansible==1.0.6) (5.3.1)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jinja2->ansible->git-acp-ansible==1.0.6) (1.1.1)
Requirement already satisfied: six>=1.4.1 in /Users/federicoolivieri/Library/Python/3.6/lib/python/site-packages (from cryptography->ansible->git-acp-ansible==1.0.6) (1.14.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cryptography->ansible->git-acp-ansible==1.0.6) (1.14.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography->ansible->git-acp-ansible==1.0.6) (2.20)
Installing collected packages: git-acp-ansible
  Found existing installation: git-acp-ansible 1.0.5
    Uninstalling git-acp-ansible-1.0.5:
      Successfully uninstalled git-acp-ansible-1.0.5
Successfully installed git-acp-ansible-1.0.6
```

**Comment by tp99** [comment]
Thanks, it worked after few tries. I tested it and ssh works now. But I'm not able to test the "Local" if stmt since I don't have it setup. It should work though. Please test if you can.
