### ISSUE TITLE
Create ansible-galaxy collection

### ISSUE THREAD

**Issue by craigers521** [lvrfrc87/git-acp-ansible#20]
i was wondering if there was a chance you could update the module in galaxy? im trying to move to galaxy for collections to help it make mobility easier to onboad other users...

also... i noticed in galaxy to get the module to work.. i had to move the git_acp.py file to the base plugins/module directory in your collection... ansible wasnt picking it up since it was inside of another directory

![image](https://user-images.githubusercontent.com/15713242/97321083-7ed62580-183c-11eb-8fae-2301fb204cb6.png)

**Comment by lvrfrc87** [comment]
I was looking for the right opportunity to do that. Seems I have it now. That would also help me to implement proper test. I will let you know soon

**Comment by lvrfrc87** [comment]
@craigers521 is now available here https://galaxy.ansible.com/lvrfrc87/git_acp. I will soon merge into master. Please let me know if everything is ok

**Comment by craigers521** [comment]
Thanks Frederico - tested and working.
