### ISSUE TITLE
the url.startswith prevent use this module with our private git plateforme

### ISSUE THREAD

**Issue by an-t-oine** [lvrfrc87/git-acp-ansible#24]
Hi,

We use Tuleap with Gitolite as version-control system. 
So url doesn't start whith 'git@' or 'ssh://git@' and make this module fails.
I commented out those lines:

```
    if mode == 'ssh':
        if not url.startswith(('git@', 'ssh://git@')):
            module.fail_json(
                msg='SSH mode selected but url (' + url + ') not starting with git@ or ssh://git@'
                )
```
it works now.

**Comment by lvrfrc87** [comment]
@an-t-oine Thanks for that! Can you please give a URL example you are using ?

**Comment by an-t-oine** [comment]
our URL are like that:

`ssh://gitolite@forge.my-company.com/my_repo/folders/.../xxx.git`

it would nice if we just check that the URL respect the format: `ssh://any_word@any_word.any_word/xxx/yyy/zzz.git`
Maybe use a regex for that: `ssh:\/\/[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+\.git`

**Comment by lvrfrc87** [comment]
Hi @an-t-oine ,
I have just uploaded Version 1.1.1 with support for Gitolite SSH URL. Would you mind to install the new version and give a try?
Thanks!

**Comment by an-t-oine** [comment]
hi,
it works fine !!!
thanks for the quickness.
