### ISSUE TITLE
GIT Non-Standard SSH Port

### ISSUE THREAD

**Issue by kziame175** [lvrfrc87/git-acp-ansible#5]
I'm trying to use a non-standard SSH port with this module for GIT repo and its defaulting to the 22 port for SSH.  I'm using git@gitaddress:port/foldertogit/something.git

Is there a way to use a non-standard ssh port with this module?

**Comment by lvrfrc87** [comment]
Can you please paste the `git_acp` task? Do you get any error? If yes, which one?

**Comment by kziame175** [comment]
This was my mistake.  What I needed was "ssh://" in front of git@gitaddress:port/foldertogit/something.git
