### ISSUE TITLE
why withdrawl ansible repo merge?

### ISSUE THREAD

**Issue by bluealein56** [lvrfrc87/git-acp-ansible#58]
I have found this repo very interesting, and read you medium blog post on it. if you don't mind me asking, why did you withdrawal your merge request from the ansible repo like you mentioned here?

https://lvrfrc87.medium.com/git-add-commit-and-push-with-ansible-67861c5e0782

**Comment by lvrfrc87** [comment]
Here the answer: https://lvrfrc87.medium.com/why-is-it-so-damn-difficult-to-get-an-ansible-pr-approved-b47dfe71dbe8 
:D

Thanks for showing appreciation on the work done so far!

**Comment by lvrfrc87** [comment]
@bluealein56 anything else I can help you with?

**Comment by bluealein56** [comment]
No I think that's it's. Planning on using this in an upcoming project and just wanted to get some insight. And also see if this repo was going to be kept current and up to date.
