### ISSUE TITLE
url support http

### ISSUE THREAD

**Issue by zou-can** [lvrfrc87/git-acp-ansible#60]
Currently only `ssh`, `https` and `local` are supported, could you add `http` type?

**Comment by lvrfrc87** [comment]
Hello!
In version `2.0.0` this will not be a problem anymore: https://github.com/lvrfrc87/git-acp-ansible/pull/57

I hope to release in the coming week.

**Comment by lvrfrc87** [comment]
Is now supported in `latest` version. `mode` argument is gone, so you can set `http` in the URL directly. Have a look to the examples and integration test. Please, let me know if you have further questions
