### ISSUE TITLE
request for adding --force in push operation

### ISSUE THREAD

**Issue by rssh22** [lvrfrc87/git-acp-ansible#61]
It would be a nice feature to be able to force a push. Maybe by setting a parameter module name push_force: [true|false].

**Comment by lvrfrc87** [comment]
`push_option` argument was actually already supported in previous version. Can you give a try and let me know if you have any problem?

**Comment by rssh22** [comment]
Hi,

I think that's a little bit confusing. push_options, according to git doc, are intended for other use cases:

`--push-option=<option>
Transmit the given string to the server, which passes them to the pre-receive as well as the post-receive hook. The given string must not contain a NUL or LF character. When multiple --push-option=<option> are given, they are all sent to the other side in the order listed on the command line. When no --push-option=<option> is given from the command line, the values of configuration variable push.pushOption are used instead.` 

May you clarify the purpose of push_option parameter in the module?

**Comment by lvrfrc87** [comment]
Sorry, my bad! Was a while that I did not work at the code :) I believe a `force=True` argument could be a good solution.

`--push-option` is something I needed for a project where I had to push commits without trigger the pipeline. Was something like `--push-option=ci.disabled`

**Comment by lvrfrc87** [comment]
`push_force` argument has been added in `2.1.0`

Federico
