### ISSUE TITLE
Add support for staging files without pushing

### ISSUE THREAD

**Issue by tom0010** [lvrfrc87/git-acp-ansible#63]
Currently it looks like it will always push after each `add`, this means we cannot pass different commit messages for different files when we add to the index, unless we push multiple times, which is not always desirable. 

It would be good if we could add support for just adding files into the index without pushing. Then add another task to push explicitly when we are ready. 

I'm proposing something like a `push` param, as we already have `add` and `pull`, I think this makes the most sense. 

If we do this, we should probably set the `push` as a default of `true`, meaning this would not be a breaking change.

**Comment by lvrfrc87** [comment]
Thanks for raising this. This is what actually this module needs: more use cases to cover. You proposal is reasonable and make sense. I will draft a PR unless you want to do it.

Federico

**Comment by tom0010** [comment]
Happy to do a PR, I have something already 🙂

**Comment by lvrfrc87** [comment]
Great! Just make sure to use the latest version that has been released few days ago (2.0.0)
