### ISSUE TITLE
Potential credential leak

### ISSUE THREAD

**Issue by MPStudyly** [lvrfrc87/git-acp-ansible#68]
Hi, we've just recently forked this repository and found a suspicious looking line in your deployment scripts:

https://github.com/lvrfrc87/git-acp-ansible/blob/0d444c855db4796d4f1b0a4400737516bbdcf6af/deployment/master.sh#LL5C25-L5C25

As we never worked with Ansible Galaxy as creators yet, we do not know, what this token allows to do, but it seems it might grant push access to your Galaxy account, which would mean anyone could update the module on your behalf. I hope we made a wrong assumption with this. Also sorry for reaching out via issue, but we were unable to look up any other contact information besides your Linkedin account, which we don't use (i.e. have no accounts to get your details shown).

Best regards

**Comment by lvrfrc87** [comment]
Thank you a lot for raising this. 

The token you pointed is an old one and been deactivated time ago. It was due to a late night push :D
