### ISSUE TITLE
push_option: not working correctly

### ISSUE THREAD

**Issue by reneschulzottogroup** [lvrfrc87/git-acp-ansible#72]
Hi,

We used git-acp-ansible v1.1.2 from the source pypi.org and created a push with special options:

push_option: --allow-empty --no-verify

After updating to git-acp-ansible v2.1.0 from github.com/lvrfrc87, the --allow-empty option no longer works.

It doesn't work as a single parameter or with the order changed. It will always be ignored.

Best regards,
René

**Comment by lvrfrc87** [comment]
Hello,

Can you please update to the latest version and let me know? As far as I am aware, it should working fine. 
Thanks

**Comment by reneschulzottogroup** [comment]
Hi lvrfrc87, I took a look to th py Script. The parameter --allow-empty s a part of the commit operation. The push_option: relates to the git push push_option=dict(default=None, type="str"),

command = [self.git_path, "commit", "-m", comment]
command.insert(3, "--push-option={0} ".format(push_option))

So the parameter could not work, for empty commit messages.

I did not take a view to the old code, but I think it was a bug and not a feature over "push_option:" to handle empty commit messages, but it was working.

It would be gerat, if you implement also a commit_option: switch.

Best regards; René

**Comment by lvrfrc87** [comment]
@reneschulzottogroup  So,if I understand correctly you are asking to support `--allow-empty` commit. Is that correct?

**Comment by lvrfrc87** [comment]
Refactor `push_options` as per #76

**Comment by lvrfrc87** [comment]
This is fixed in Ver. 2.3.0

**Comment by reneschulzottogroup** [comment]
very nice!
