### ISSUE TITLE
Ability to add -f/--force

### ISSUE THREAD

**Issue by Abyss777** [lvrfrc87/git-acp-ansible#76]
Hello if I need to add some file in "gitignored" folder `/foo` i use `git add -f /foo/bar`

Is it possible to do the same with `git_acp` ?

**Comment by lvrfrc87** [comment]
Hello @Abyss777. sorry for the late response. I will work on this and let you know once done

**Comment by lvrfrc87** [comment]
The idea is to add `add_options` args which takes a `dict` where key is the option and value the parameter. Example

`add_options: {"-f": "path"}`

**Comment by lvrfrc87** [comment]
This will go with Version 2.3.0
