### ISSUE TITLE
feature request: please support fileglob in "add" function

### ISSUE THREAD

**Issue by cvernooy23** [lvrfrc87/git-acp-ansible#9]
thank you for writing this module! just trying it out for the first time. One thing that would be helpful is to support fileglob and wildcards in the git add function. Currently we need to use the find shell command to build the list of files (your function could do that behind the scenes) or use "with_fileglob" but that could result in multiple pushes for a single run, based on how many files were changed.

that being said this looks awesome, nice to get away from using shell commands for push operations!

**Comment by lvrfrc87** [comment]
Hello,
Could you please list the commands you would like to add or the step by step manual process you do in order to add files?

**Comment by cvernooy23** [comment]
it's a normal git operation to push to the repo, but the files are inherently in a different directory than the ansible automation so "git add ." doesn't work. the automation I'm writing creates a bunch of output that has to be synced but the automation itself is held in a separate repository, which is by design. Sure, I could explicitely define each file as of today, but that reduces the flexibility to say "I want to add, commit, push everything in xyz directory"

**Comment by lvrfrc87** [comment]
Ok. I am doing something similar in my playbook to find some type of file. 
In the module, you can use all the wildcards supported by `git add` command: https://git-scm.com/docs/git-add#_examples

Adding some `find` intelligence to the module I believe could be confusing as we would mix `git` operations with `find` commands.

**Comment by lvrfrc87** [comment]
@cvernooy23 I have just found this one: https://docs.ansible.com/ansible/latest/plugins/lookup/fileglob.html
Seems that Ansible supports `with_fileglob`. Can you try to replace your `find` with `with_fileglob` and let me know if it works ok?
